"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import cosmos.base.query.v1beta1.pagination_pb2
import cosmos.feegrant.v1beta1.feegrant_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

# QueryAllowanceRequest is the request type for the Query/Allowance RPC method.
class QueryAllowanceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    GRANTER_FIELD_NUMBER: builtins.int
    GRANTEE_FIELD_NUMBER: builtins.int
    # granter is the address of the user granting an allowance of their funds.
    granter: typing.Text = ...
    # grantee is the address of the user being granted an allowance of another user's funds.
    grantee: typing.Text = ...
    def __init__(self,
        *,
        granter : typing.Text = ...,
        grantee : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"grantee",b"grantee",u"granter",b"granter"]) -> None: ...
global___QueryAllowanceRequest = QueryAllowanceRequest

# QueryAllowanceResponse is the response type for the Query/Allowance RPC method.
class QueryAllowanceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ALLOWANCE_FIELD_NUMBER: builtins.int
    # allowance is a allowance granted for grantee by granter.
    @property
    def allowance(self) -> cosmos.feegrant.v1beta1.feegrant_pb2.Grant: ...
    def __init__(self,
        *,
        allowance : typing.Optional[cosmos.feegrant.v1beta1.feegrant_pb2.Grant] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"allowance",b"allowance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"allowance",b"allowance"]) -> None: ...
global___QueryAllowanceResponse = QueryAllowanceResponse

# QueryAllowancesRequest is the request type for the Query/Allowances RPC method.
class QueryAllowancesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    GRANTEE_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    grantee: typing.Text = ...
    # pagination defines an pagination for the request.
    @property
    def pagination(self) -> cosmos.base.query.v1beta1.pagination_pb2.PageRequest: ...
    def __init__(self,
        *,
        grantee : typing.Text = ...,
        pagination : typing.Optional[cosmos.base.query.v1beta1.pagination_pb2.PageRequest] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"pagination",b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"grantee",b"grantee",u"pagination",b"pagination"]) -> None: ...
global___QueryAllowancesRequest = QueryAllowancesRequest

# QueryAllowancesResponse is the response type for the Query/Allowances RPC method.
class QueryAllowancesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ALLOWANCES_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    # allowances are allowance's granted for grantee by granter.
    @property
    def allowances(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[cosmos.feegrant.v1beta1.feegrant_pb2.Grant]: ...
    # pagination defines an pagination for the response.
    @property
    def pagination(self) -> cosmos.base.query.v1beta1.pagination_pb2.PageResponse: ...
    def __init__(self,
        *,
        allowances : typing.Optional[typing.Iterable[cosmos.feegrant.v1beta1.feegrant_pb2.Grant]] = ...,
        pagination : typing.Optional[cosmos.base.query.v1beta1.pagination_pb2.PageResponse] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"pagination",b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"allowances",b"allowances",u"pagination",b"pagination"]) -> None: ...
global___QueryAllowancesResponse = QueryAllowancesResponse
