"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .query_pb2 import *
class QueryStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    DenomTrace:grpc.UnaryUnaryMultiCallable[
        global___QueryDenomTraceRequest,
        global___QueryDenomTraceResponse] = ...

    DenomTraces:grpc.UnaryUnaryMultiCallable[
        global___QueryDenomTracesRequest,
        global___QueryDenomTracesResponse] = ...

    Params:grpc.UnaryUnaryMultiCallable[
        global___QueryParamsRequest,
        global___QueryParamsResponse] = ...


class QueryServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def DenomTrace(self,
        request: global___QueryDenomTraceRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryDenomTraceResponse: ...

    @abc.abstractmethod
    def DenomTraces(self,
        request: global___QueryDenomTracesRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryDenomTracesResponse: ...

    @abc.abstractmethod
    def Params(self,
        request: global___QueryParamsRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryParamsResponse: ...


def add_QueryServicer_to_server(servicer: QueryServicer, server: grpc.Server) -> None: ...
