"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .query_pb2 import *
# Query defines the gRPC upgrade querier service.
class QueryStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    # CurrentPlan queries the current upgrade plan.
    CurrentPlan:grpc.UnaryUnaryMultiCallable[
        global___QueryCurrentPlanRequest,
        global___QueryCurrentPlanResponse] = ...

    # AppliedPlan queries a previously applied upgrade plan by its name.
    AppliedPlan:grpc.UnaryUnaryMultiCallable[
        global___QueryAppliedPlanRequest,
        global___QueryAppliedPlanResponse] = ...

    # UpgradedConsensusState queries the consensus state that will serve
    # as a trusted kernel for the next version of this chain. It will only be
    # stored at the last height of this chain.
    # UpgradedConsensusState RPC not supported with legacy querier
    # This rpc is deprecated now that IBC has its own replacement
    # (https://github.com/cosmos/ibc-go/blob/2c880a22e9f9cc75f62b527ca94aa75ce1106001/proto/ibc/core/client/v1/query.proto#L54)
    UpgradedConsensusState:grpc.UnaryUnaryMultiCallable[
        global___QueryUpgradedConsensusStateRequest,
        global___QueryUpgradedConsensusStateResponse] = ...

    # ModuleVersions queries the list of module versions from state.
    ModuleVersions:grpc.UnaryUnaryMultiCallable[
        global___QueryModuleVersionsRequest,
        global___QueryModuleVersionsResponse] = ...


# Query defines the gRPC upgrade querier service.
class QueryServicer(metaclass=abc.ABCMeta):
    # CurrentPlan queries the current upgrade plan.
    @abc.abstractmethod
    def CurrentPlan(self,
        request: global___QueryCurrentPlanRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryCurrentPlanResponse: ...

    # AppliedPlan queries a previously applied upgrade plan by its name.
    @abc.abstractmethod
    def AppliedPlan(self,
        request: global___QueryAppliedPlanRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryAppliedPlanResponse: ...

    # UpgradedConsensusState queries the consensus state that will serve
    # as a trusted kernel for the next version of this chain. It will only be
    # stored at the last height of this chain.
    # UpgradedConsensusState RPC not supported with legacy querier
    # This rpc is deprecated now that IBC has its own replacement
    # (https://github.com/cosmos/ibc-go/blob/2c880a22e9f9cc75f62b527ca94aa75ce1106001/proto/ibc/core/client/v1/query.proto#L54)
    @abc.abstractmethod
    def UpgradedConsensusState(self,
        request: global___QueryUpgradedConsensusStateRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryUpgradedConsensusStateResponse: ...

    # ModuleVersions queries the list of module versions from state.
    @abc.abstractmethod
    def ModuleVersions(self,
        request: global___QueryModuleVersionsRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryModuleVersionsResponse: ...


def add_QueryServicer_to_server(servicer: QueryServicer, server: grpc.Server) -> None: ...
