"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .query_pb2 import *
class QueryStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Params:grpc.UnaryUnaryMultiCallable[
        global___QueryParamsRequest,
        global___QueryParamsResponse] = ...

    SigningInfo:grpc.UnaryUnaryMultiCallable[
        global___QuerySigningInfoRequest,
        global___QuerySigningInfoResponse] = ...

    SigningInfos:grpc.UnaryUnaryMultiCallable[
        global___QuerySigningInfosRequest,
        global___QuerySigningInfosResponse] = ...


class QueryServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Params(self,
        request: global___QueryParamsRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryParamsResponse: ...

    @abc.abstractmethod
    def SigningInfo(self,
        request: global___QuerySigningInfoRequest,
        context: grpc.ServicerContext,
    ) -> global___QuerySigningInfoResponse: ...

    @abc.abstractmethod
    def SigningInfos(self,
        request: global___QuerySigningInfosRequest,
        context: grpc.ServicerContext,
    ) -> global___QuerySigningInfosResponse: ...


def add_QueryServicer_to_server(servicer: QueryServicer, server: grpc.Server) -> None: ...
