"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .tx_pb2 import *
class MsgStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Unjail:grpc.UnaryUnaryMultiCallable[
        global___MsgUnjail,
        global___MsgUnjailResponse] = ...


class MsgServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Unjail(self,
        request: global___MsgUnjail,
        context: grpc.ServicerContext,
    ) -> global___MsgUnjailResponse: ...


def add_MsgServicer_to_server(servicer: MsgServicer, server: grpc.Server) -> None: ...
