"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .tx_pb2 import *
# Msg defines the slashing Msg service.
class MsgStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    # Unjail defines a method for unjailing a jailed validator, thus returning
    # them into the bonded validator set, so they can begin receiving provisions
    # and rewards again.
    Unjail:grpc.UnaryUnaryMultiCallable[
        global___MsgUnjail,
        global___MsgUnjailResponse] = ...


# Msg defines the slashing Msg service.
class MsgServicer(metaclass=abc.ABCMeta):
    # Unjail defines a method for unjailing a jailed validator, thus returning
    # them into the bonded validator set, so they can begin receiving provisions
    # and rewards again.
    @abc.abstractmethod
    def Unjail(self,
        request: global___MsgUnjail,
        context: grpc.ServicerContext,
    ) -> global___MsgUnjailResponse: ...


def add_MsgServicer_to_server(servicer: MsgServicer, server: grpc.Server) -> None: ...
