"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .query_pb2 import *
# Query defines the gRPC querier service for gov module
class QueryStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    # Proposal queries proposal details based on ProposalID.
    Proposal:grpc.UnaryUnaryMultiCallable[
        global___QueryProposalRequest,
        global___QueryProposalResponse] = ...

    # Proposals queries all proposals based on given status.
    Proposals:grpc.UnaryUnaryMultiCallable[
        global___QueryProposalsRequest,
        global___QueryProposalsResponse] = ...

    # Vote queries voted information based on proposalID, voterAddr.
    Vote:grpc.UnaryUnaryMultiCallable[
        global___QueryVoteRequest,
        global___QueryVoteResponse] = ...

    # Votes queries votes of a given proposal.
    Votes:grpc.UnaryUnaryMultiCallable[
        global___QueryVotesRequest,
        global___QueryVotesResponse] = ...

    # Params queries all parameters of the gov module.
    Params:grpc.UnaryUnaryMultiCallable[
        global___QueryParamsRequest,
        global___QueryParamsResponse] = ...

    # Deposit queries single deposit information based proposalID, depositAddr.
    Deposit:grpc.UnaryUnaryMultiCallable[
        global___QueryDepositRequest,
        global___QueryDepositResponse] = ...

    # Deposits queries all deposits of a single proposal.
    Deposits:grpc.UnaryUnaryMultiCallable[
        global___QueryDepositsRequest,
        global___QueryDepositsResponse] = ...

    # TallyResult queries the tally of a proposal vote.
    TallyResult:grpc.UnaryUnaryMultiCallable[
        global___QueryTallyResultRequest,
        global___QueryTallyResultResponse] = ...


# Query defines the gRPC querier service for gov module
class QueryServicer(metaclass=abc.ABCMeta):
    # Proposal queries proposal details based on ProposalID.
    @abc.abstractmethod
    def Proposal(self,
        request: global___QueryProposalRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryProposalResponse: ...

    # Proposals queries all proposals based on given status.
    @abc.abstractmethod
    def Proposals(self,
        request: global___QueryProposalsRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryProposalsResponse: ...

    # Vote queries voted information based on proposalID, voterAddr.
    @abc.abstractmethod
    def Vote(self,
        request: global___QueryVoteRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryVoteResponse: ...

    # Votes queries votes of a given proposal.
    @abc.abstractmethod
    def Votes(self,
        request: global___QueryVotesRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryVotesResponse: ...

    # Params queries all parameters of the gov module.
    @abc.abstractmethod
    def Params(self,
        request: global___QueryParamsRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryParamsResponse: ...

    # Deposit queries single deposit information based proposalID, depositAddr.
    @abc.abstractmethod
    def Deposit(self,
        request: global___QueryDepositRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryDepositResponse: ...

    # Deposits queries all deposits of a single proposal.
    @abc.abstractmethod
    def Deposits(self,
        request: global___QueryDepositsRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryDepositsResponse: ...

    # TallyResult queries the tally of a proposal vote.
    @abc.abstractmethod
    def TallyResult(self,
        request: global___QueryTallyResultRequest,
        context: grpc.ServicerContext,
    ) -> global___QueryTallyResultResponse: ...


def add_QueryServicer_to_server(servicer: QueryServicer, server: grpc.Server) -> None: ...
