"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import cosmos.mint.v1beta1.mint_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

# QueryParamsRequest is the request type for the Query/Params RPC method.
class QueryParamsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___QueryParamsRequest = QueryParamsRequest

# QueryParamsResponse is the response type for the Query/Params RPC method.
class QueryParamsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PARAMS_FIELD_NUMBER: builtins.int
    # params defines the parameters of the module.
    @property
    def params(self) -> cosmos.mint.v1beta1.mint_pb2.Params: ...
    def __init__(self,
        *,
        params : typing.Optional[cosmos.mint.v1beta1.mint_pb2.Params] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"params",b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"params",b"params"]) -> None: ...
global___QueryParamsResponse = QueryParamsResponse

# QueryInflationRequest is the request type for the Query/Inflation RPC method.
class QueryInflationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___QueryInflationRequest = QueryInflationRequest

# QueryInflationResponse is the response type for the Query/Inflation RPC
# method.
class QueryInflationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INFLATION_FIELD_NUMBER: builtins.int
    # inflation is the current minting inflation value.
    inflation: builtins.bytes = ...
    def __init__(self,
        *,
        inflation : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"inflation",b"inflation"]) -> None: ...
global___QueryInflationResponse = QueryInflationResponse

# QueryAnnualProvisionsRequest is the request type for the
# Query/AnnualProvisions RPC method.
class QueryAnnualProvisionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___QueryAnnualProvisionsRequest = QueryAnnualProvisionsRequest

# QueryAnnualProvisionsResponse is the response type for the
# Query/AnnualProvisions RPC method.
class QueryAnnualProvisionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ANNUAL_PROVISIONS_FIELD_NUMBER: builtins.int
    # annual_provisions is the current minting annual provisions value.
    annual_provisions: builtins.bytes = ...
    def __init__(self,
        *,
        annual_provisions : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"annual_provisions",b"annual_provisions"]) -> None: ...
global___QueryAnnualProvisionsResponse = QueryAnnualProvisionsResponse
