"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .query_pb2 import *
# Service defines the gRPC querier service for tendermint queries.
class ServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    # GetNodeInfo queries the current node info.
    GetNodeInfo:grpc.UnaryUnaryMultiCallable[
        global___GetNodeInfoRequest,
        global___GetNodeInfoResponse] = ...

    # GetSyncing queries node syncing.
    GetSyncing:grpc.UnaryUnaryMultiCallable[
        global___GetSyncingRequest,
        global___GetSyncingResponse] = ...

    # GetLatestBlock returns the latest block.
    GetLatestBlock:grpc.UnaryUnaryMultiCallable[
        global___GetLatestBlockRequest,
        global___GetLatestBlockResponse] = ...

    # GetBlockByHeight queries block for given height.
    GetBlockByHeight:grpc.UnaryUnaryMultiCallable[
        global___GetBlockByHeightRequest,
        global___GetBlockByHeightResponse] = ...

    # GetLatestValidatorSet queries latest validator-set.
    GetLatestValidatorSet:grpc.UnaryUnaryMultiCallable[
        global___GetLatestValidatorSetRequest,
        global___GetLatestValidatorSetResponse] = ...

    # GetValidatorSetByHeight queries validator-set at a given height.
    GetValidatorSetByHeight:grpc.UnaryUnaryMultiCallable[
        global___GetValidatorSetByHeightRequest,
        global___GetValidatorSetByHeightResponse] = ...


# Service defines the gRPC querier service for tendermint queries.
class ServiceServicer(metaclass=abc.ABCMeta):
    # GetNodeInfo queries the current node info.
    @abc.abstractmethod
    def GetNodeInfo(self,
        request: global___GetNodeInfoRequest,
        context: grpc.ServicerContext,
    ) -> global___GetNodeInfoResponse: ...

    # GetSyncing queries node syncing.
    @abc.abstractmethod
    def GetSyncing(self,
        request: global___GetSyncingRequest,
        context: grpc.ServicerContext,
    ) -> global___GetSyncingResponse: ...

    # GetLatestBlock returns the latest block.
    @abc.abstractmethod
    def GetLatestBlock(self,
        request: global___GetLatestBlockRequest,
        context: grpc.ServicerContext,
    ) -> global___GetLatestBlockResponse: ...

    # GetBlockByHeight queries block for given height.
    @abc.abstractmethod
    def GetBlockByHeight(self,
        request: global___GetBlockByHeightRequest,
        context: grpc.ServicerContext,
    ) -> global___GetBlockByHeightResponse: ...

    # GetLatestValidatorSet queries latest validator-set.
    @abc.abstractmethod
    def GetLatestValidatorSet(self,
        request: global___GetLatestValidatorSetRequest,
        context: grpc.ServicerContext,
    ) -> global___GetLatestValidatorSetResponse: ...

    # GetValidatorSetByHeight queries validator-set at a given height.
    @abc.abstractmethod
    def GetValidatorSetByHeight(self,
        request: global___GetValidatorSetByHeightRequest,
        context: grpc.ServicerContext,
    ) -> global___GetValidatorSetByHeightResponse: ...


def add_ServiceServicer_to_server(servicer: ServiceServicer, server: grpc.Server) -> None: ...
