"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import cosmos.authz.v1beta1.authz_pb2
import cosmos.base.query.v1beta1.pagination_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

# QueryGrantsRequest is the request type for the Query/Grants RPC method.
class QueryGrantsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    GRANTER_FIELD_NUMBER: builtins.int
    GRANTEE_FIELD_NUMBER: builtins.int
    MSG_TYPE_URL_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    granter: typing.Text = ...
    grantee: typing.Text = ...
    # Optional, msg_type_url, when set, will query only grants matching given msg type.
    msg_type_url: typing.Text = ...
    # pagination defines an pagination for the request.
    @property
    def pagination(self) -> cosmos.base.query.v1beta1.pagination_pb2.PageRequest: ...
    def __init__(self,
        *,
        granter : typing.Text = ...,
        grantee : typing.Text = ...,
        msg_type_url : typing.Text = ...,
        pagination : typing.Optional[cosmos.base.query.v1beta1.pagination_pb2.PageRequest] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"pagination",b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"grantee",b"grantee",u"granter",b"granter",u"msg_type_url",b"msg_type_url",u"pagination",b"pagination"]) -> None: ...
global___QueryGrantsRequest = QueryGrantsRequest

# QueryGrantsResponse is the response type for the Query/Authorizations RPC method.
class QueryGrantsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    GRANTS_FIELD_NUMBER: builtins.int
    PAGINATION_FIELD_NUMBER: builtins.int
    # authorizations is a list of grants granted for grantee by granter.
    @property
    def grants(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[cosmos.authz.v1beta1.authz_pb2.Grant]: ...
    # pagination defines an pagination for the response.
    @property
    def pagination(self) -> cosmos.base.query.v1beta1.pagination_pb2.PageResponse: ...
    def __init__(self,
        *,
        grants : typing.Optional[typing.Iterable[cosmos.authz.v1beta1.authz_pb2.Grant]] = ...,
        pagination : typing.Optional[cosmos.base.query.v1beta1.pagination_pb2.PageResponse] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"pagination",b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"grants",b"grants",u"pagination",b"pagination"]) -> None: ...
global___QueryGrantsResponse = QueryGrantsResponse
