"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .tx_pb2 import *
class MsgStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    VerifyInvariant:grpc.UnaryUnaryMultiCallable[
        global___MsgVerifyInvariant,
        global___MsgVerifyInvariantResponse] = ...


class MsgServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def VerifyInvariant(self,
        request: global___MsgVerifyInvariant,
        context: grpc.ServicerContext,
    ) -> global___MsgVerifyInvariantResponse: ...


def add_MsgServicer_to_server(servicer: MsgServicer, server: grpc.Server) -> None: ...
