name: PyBand Workflow
on: pull_request

jobs:
  pyband-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Install libs
        run: |
          sudo apt update
          sudo apt install -y python3-dev libsecp256k1-dev
      
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev
      
      - name: Run tests
        run: uv run pytest tests
